version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
    image: minicli-php8-dev
    restart: unless-stopped
    working_dir: /home/sammy
    volumes:
      - ./:/home/sammy
    networks:
      - minicli-dev

networks:
  minicli-dev:
    driver: bridge
